name: Repositories Migration to GHEC [GEI]

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  contents: read

jobs: 
  migrate:
    if: contains(github.event.issue.labels.*.name, 'migration') && 
        contains(github.event.issue.labels.*.name, 'gei') && 
        startsWith(github.event.comment.body, '/migrate-repositories')
    uses: ./.github/workflows/shared-github-enterprise-cloud-gei.yml
    secrets:
      TARGET_ADMIN_TOKEN: ${{ secrets.TARGET_ADMIN_TOKEN }}
      SOURCE_ADMIN_TOKEN: ${{ secrets.SOURCE_ADMIN_TOKEN }}
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  check-command:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'migration') && 
        contains(github.event.issue.labels.*.name, 'gei')
    steps:
      - name: Check for migrate command
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const comment = context.payload.comment.body.trim().toLowerCase();
            if (!comment.startsWith('/migrate-repositories')) {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Invalid command. Please use "/migrate-repositories" to start the migration process.'
              });
            }
